# AI Agents Service Accounts and RBAC Configuration
# Defines service accounts for various AI agent types with appropriate permissions

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-orchestrator
  namespace: ai-agents
  labels:
    app: ai-agent-orchestrator
    agent-type: orchestrator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-coding
  namespace: ai-agents
  labels:
    app: ai-agent-coding
    agent-type: coding
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-testing
  namespace: ai-agents
  labels:
    app: ai-agent-testing
    agent-type: testing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-security
  namespace: ai-agents
  labels:
    app: ai-agent-security
    agent-type: security
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-compliance
  namespace: ai-agents
  labels:
    app: ai-agent-compliance
    agent-type: compliance
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-documentation
  namespace: ai-agents
  labels:
    app: ai-agent-documentation
    agent-type: documentation
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-discovery
  namespace: ai-agents
  labels:
    app: ai-agent-discovery
    agent-type: discovery
---
# Cluster Role for AI Agents
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ai-agent-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
# Cluster Role Bindings for each agent type
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-agent-orchestrator-binding
subjects:
- kind: ServiceAccount
  name: ai-agent-orchestrator
  namespace: ai-agents
roleRef:
  kind: ClusterRole
  name: ai-agent-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-agent-coding-binding
subjects:
- kind: ServiceAccount
  name: ai-agent-coding
  namespace: ai-agents
roleRef:
  kind: ClusterRole
  name: ai-agent-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-agent-testing-binding
subjects:
- kind: ServiceAccount
  name: ai-agent-testing
  namespace: ai-agents
roleRef:
  kind: ClusterRole
  name: ai-agent-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-agent-security-binding
subjects:
- kind: ServiceAccount
  name: ai-agent-security
  namespace: ai-agents
roleRef:
  kind: ClusterRole
  name: ai-agent-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-agent-compliance-binding
subjects:
- kind: ServiceAccount
  name: ai-agent-compliance
  namespace: ai-agents
roleRef:
  kind: ClusterRole
  name: ai-agent-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-agent-documentation-binding
subjects:
- kind: ServiceAccount
  name: ai-agent-documentation
  namespace: ai-agents
roleRef:
  kind: ClusterRole
  name: ai-agent-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-agent-discovery-binding
subjects:
- kind: ServiceAccount
  name: ai-agent-discovery
  namespace: ai-agents
roleRef:
  kind: ClusterRole
  name: ai-agent-role
  apiGroup: rbac.authorization.k8s.io